/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.realtime.jsonc --config=wrangler.jsonc --env-file=realtime/.dev.vars.example --include-runtime=false --env-interface=RealtimeEnv realtime-configuration.d.ts` (hash: 970fe7eae90ca5f9e45ba168c8a04976)
interface __BaseEnv_RealtimeEnv {
	REALTIME_RELEASE_ID: "local";
	GATEWAY_ORIGIN: "http://localhost:8787";
	REALTIME_SESSION: DurableObjectNamespace<import("./src/realtime/worker").RealtimeSession>;
	BACKEND: Service<typeof import("./src/index").RealtimeBackend>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/realtime/worker");
		durableNamespaces: "RealtimeSession";
	}
	interface Env extends __BaseEnv_RealtimeEnv {}
}
interface RealtimeEnv extends __BaseEnv_RealtimeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REALTIME_RELEASE_ID" | "GATEWAY_ORIGIN">> {}
}
