// Generated by openapi:generate. Do not edit.
export const INFERENCE_ROUTES = {
  "connectRealtime": "/v1/apps/:app/realtime/:provider",
  "proxyProviderRequest": "/v1/apps/:app/proxy/:provider/*",
  "callNamedEndpoint": "/v1/apps/:app/endpoints/:slug"
} as const;
