import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { CATALOG } from "../src/contracts/catalog.ts";
import { createOpenAPIDocument } from "../src/contracts/openapi.ts";

const outputDirectory = fileURLToPath(new URL("../openapi", import.meta.url));
const outputPath = fileURLToPath(new URL("../openapi/openapi.json", import.meta.url));
const document = createOpenAPIDocument();

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputPath, `${JSON.stringify(document, null, 2)}\n`);
console.log(`Generated ${outputPath}`);

const routes = Object.fromEntries(["discoverRealtime", "connectRealtime", "proxyProviderRequest", "callNamedEndpoint"].map(name => {
  const spec = CATALOG[name as keyof typeof CATALOG];
  return [name, spec.path.replace(/\{path\}/gu, "*").replace(/\{(\w+)\}/gu, ":$1")];
}));
await writeFile(fileURLToPath(new URL("../src/contracts/inference-routes.ts", import.meta.url)), `// Generated by openapi:generate. Do not edit.\nexport const INFERENCE_ROUTES = ${JSON.stringify(routes, null, 2)} as const;\n`);
